<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\DB;

class Campaign extends Model
{
    protected $fillable = [
        'nom',
        'objet',
        'contenu',
        'category_id',
        'category_ids',
        'import_log_id',
        'date_envoi',
        'statut',
        'auto_retry',
        'max_auto_retries',
        'created_by',
        'smtp_setting_id',
    ];

    protected function casts(): array
    {
        return [
            'date_envoi' => 'datetime',
            'category_ids' => 'array',
            'auto_retry' => 'boolean',
            'max_auto_retries' => 'integer',
        ];
    }

    /**
     * Get the target list/category for this campaign.
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the target import file/batch for this campaign.
     */
    public function importLog(): BelongsTo
    {
        return $this->belongsTo(ImportLog::class, 'import_log_id');
    }

    public function importBatch(): BelongsTo
    {
        return $this->importLog();
    }

    public function getImportBatchIdAttribute()
    {
        return $this->import_log_id;
    }

    public function setImportBatchIdAttribute($value): void
    {
        $this->import_log_id = $value;
    }

    public function categoryIds(): array
    {
        if (! empty($this->category_ids)) {
            return array_values(array_filter(array_map('intval', (array) $this->category_ids)));
        }

        if (! empty($this->category_id)) {
            return [(int) $this->category_id];
        }

        return [];
    }

    /**
     * Get the email logs generated by this campaign.
     */
    public function emailLogs(): HasMany
    {
        return $this->hasMany(EmailLog::class);
    }

    /**
     * Get the failed email logs for this campaign.
     */
    public function failedEmailLogs(): HasMany
    {
        return $this->hasMany(EmailLog::class)->whereIn('status', [
            EmailLog::STATUS_FAILED,
            EmailLog::STATUS_BOUNCED,
        ]);
    }

    /**
     * Get the attachments for this campaign.
     */
    public function attachments(): HasMany
    {
        return $this->hasMany(CampaignAttachment::class);
    }

    /**
     * Get the user who created the campaign.
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Get the explicitly assigned SMTP setting for this campaign.
     */
    public function smtpSetting(): BelongsTo
    {
        return $this->belongsTo(SmtpSetting::class);
    }

    /**
     * Resolve the active SMTP setting for this campaign:
     * 1. Explicitly assigned on campaign
     * 2. Creator's personal SMTP setting
     * 3. System default active SMTP setting
     */
    public function resolveSmtpSetting(): ?SmtpSetting
    {
        if ($this->smtp_setting_id && $this->smtpSetting) {
            return $this->smtpSetting;
        }

        if ($this->relationLoaded('creator') && $this->creator?->smtpSetting) {
            return $this->creator->smtpSetting;
        }

        if ($this->created_by) {
            $creator = $this->creator ?? User::find($this->created_by);
            if ($creator?->smtpSetting) {
                return $creator->smtpSetting;
            }
        }

        return SmtpSetting::where('is_active', true)->whereNull('user_id')->first()
            ?? SmtpSetting::where('is_active', true)->first();
    }

    public function markAsSentIfAllEmailsAreSent(): bool
    {
        // Single conditional UPDATE — avoids two SELECT queries.
        // Uses a NOT EXISTS subquery so we only flip to "envoyee"
        // when there are logs AND none are still pending.
        $updated = \Illuminate\Support\Facades\DB::table('campaigns')
            ->where('id', $this->id)
            ->where('statut', 'en_cours')
            ->whereExists(function ($query) {
                $query->select(\Illuminate\Support\Facades\DB::raw(1))
                    ->from('email_logs')
                    ->whereColumn('email_logs.campaign_id', 'campaigns.id');
            })
            ->whereNotExists(function ($query) {
                $query->select(\Illuminate\Support\Facades\DB::raw(1))
                    ->from('email_logs')
                    ->whereColumn('email_logs.campaign_id', 'campaigns.id')
                    ->where('email_logs.status', EmailLog::STATUS_PENDING);
            })
            ->update(['statut' => 'envoyee', 'updated_at' => now()]);

        return $updated > 0;
    }

    public function sentCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_SENT)->count();
    }

    public function deliveredCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_DELIVERED)->count();
    }

    public function bouncedCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_BOUNCED)->count();
    }

    public function invalidCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_INVALID)->count();
    }

    /**
     * Scope a query to only include campaigns visible to the given user.
     * Administrators can see all campaigns; standard users only see campaigns they created.
     */
    public function scopeForUser($query, ?User $user = null)
    {
        $user = $user ?? auth()->user();

        if (! $user) {
            return $query->whereRaw('1 = 0');
        }

        if ($user->hasRole('admin')) {
            return $query;
        }

        return $query->where('created_by', $user->id);
    }

    /**
     * Check if the campaign is owned by the given user.
     */
    public function isOwnedBy($user): bool
    {
        $userId = $user instanceof User ? $user->id : (int) $user;
        return (int) $this->created_by === $userId;
    }
}
