<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Campaign extends Model
{
    protected $fillable = [
        'nom',
        'objet',
        'contenu',
        'category_id',
        'category_ids',
        'import_log_id',
        'date_envoi',
        'statut',
        'auto_retry',
        'max_auto_retries',
        'created_by'
    ];

    protected function casts(): array
    {
        return [
            'date_envoi' => 'datetime',
            'category_ids' => 'array',
            'auto_retry' => 'boolean',
            'max_auto_retries' => 'integer',
        ];
    }

    /**
     * Get the target list/category for this campaign.
     */
    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * Get the target import file/batch for this campaign.
     */
    public function importLog(): BelongsTo
    {
        return $this->belongsTo(ImportLog::class, 'import_log_id');
    }

    public function importBatch(): BelongsTo
    {
        return $this->importLog();
    }

    public function getImportBatchIdAttribute()
    {
        return $this->import_log_id;
    }

    public function setImportBatchIdAttribute($value): void
    {
        $this->import_log_id = $value;
    }

    public function categoryIds(): array
    {
        if (! empty($this->category_ids)) {
            return array_values(array_filter(array_map('intval', (array) $this->category_ids)));
        }

        if (! empty($this->category_id)) {
            return [(int) $this->category_id];
        }

        return [];
    }

    /**
     * Get the email logs generated by this campaign.
     */
    public function emailLogs(): HasMany
    {
        return $this->hasMany(EmailLog::class);
    }

    /**
     * Get the failed email logs for this campaign.
     */
    public function failedEmailLogs(): HasMany
    {
        return $this->hasMany(EmailLog::class)->whereIn('status', [
            EmailLog::STATUS_FAILED,
            EmailLog::STATUS_BOUNCED,
        ]);
    }

    /**
     * Get the attachments for this campaign.
     */
    public function attachments(): HasMany
    {
        return $this->hasMany(CampaignAttachment::class);
    }

    /**
     * Get the user who created the campaign.
     */
    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function markAsSentIfAllEmailsAreSent(): bool
    {
        if (! $this->emailLogs()->exists()) {
            return false;
        }

        $hasPendingEmails = $this->emailLogs()
            ->where('status', EmailLog::STATUS_PENDING)
            ->exists();

        if ($hasPendingEmails) {
            return false;
        }

        return $this->newQuery()
            ->whereKey($this->id)
            ->where('statut', 'en_cours')
            ->update(['statut' => 'envoyee']) > 0;
    }

    public function sentCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_SENT)->count();
    }

    public function deliveredCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_DELIVERED)->count();
    }

    public function bouncedCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_BOUNCED)->count();
    }

    public function invalidCount(): int
    {
        return $this->emailLogs()->where('status', EmailLog::STATUS_INVALID)->count();
    }
}
